BEGIN;
-- 用户
INSERT INTO system_user (username, password, nickname, tel, email, sex, status, is_admin, remark, create_time, update_time, delete_time) VALUES ('lanyulei', '$2a$10$7AkPs/BP4h3JQiK0K2vPLeh/qa.soqsiCllhjwvHYkfEnHo./kQo6', '兰玉磊', '', 'lanyulei@fdevops.com', 0, true, true, '', '2021-08-25 16:33:23.108187 +00:00', '2021-08-25 16:33:23.108187 +00:00', null);

-- 菜单
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('/home', 'Home', 'home/index', '', '首页', '', false, true, true, false, '{home}', 'iconfont icon-shouye', 0, 2, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('/system', 'System', 'layout/routerView/parent', '', '系统设置', '', false, true, false, false, '{system}', 'iconfont icon-xitongshezhi', 0, 1, 2, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('/system/menu', 'SystemMenu', 'system/menu/index', '', '菜单管理', '', false, true, false, false, '{system:menu}', 'el-icon-tickets', 2, 2, 15, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('/system/user', 'SystemUser', 'system/user/index', '', '用户管理', '', false, true, false, false, '{system:user}', 'el-icon-user', 2, 2, 1, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('/system/role', 'SystemRole', 'system/role/index', '', '角色管理', '', false, true, false, false, '{system:role}', 'el-icon-picture-outline-round', 2, 2, 5, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('/system/api', 'SystemAPI', 'system/api/index', '', '接口管理', '', false, true, false, false, '{system:api}', 'el-icon-s-promotion', 2, 2, 10, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('/system/role/permission/:id', 'SystemRolePermission', 'system/role/permission', '', '角色权限', '', true, true, false, false, '{system:role:permission}', 'el-icon-help', 2, 2, 4, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '新建用户', '', false, false, false, false, '{system:user:create}', '', 4, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '编辑用户', '', false, false, false, false, '{system:user:edit}', '', 4, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '删除用户', '', false, false, false, false, '{system:user:delete}', '', 4, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '新建角色', '', false, false, false, false, '{system:role:create}', '', 5, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '角色权限', '', false, false, false, false, '{system:role:permission}', '', 5, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '编辑角色', '', false, false, false, false, '{system:role:edit}', '', 5, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '删除角色', '', false, false, false, false, '{system:role:delete}', '', 5, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '新建接口', '', false, false, false, false, '{system:api:create}', '', 6, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '编辑接口', '', false, false, false, false, '{system:api:edit}', '', 6, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '删除接口', '', false, false, false, false, '{system:api:delete}', '', 6, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '接口分组列表', '', false, false, false, false, '{system:api-group:list}', '', 6, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '新建接口分组', '', false, false, false, false, '{system:api-group:create}', '', 6, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '编辑接口分组', '', false, false, false, false, '{system:api-group:edit}', '', 6, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '删除接口分组', '', false, false, false, false, '{system:api-group:delete}', '', 6, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '新建顶级菜单', '', false, false, false, false, '{system:top-menu:create}', '', 3, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '保存菜单表单', '', false, false, false, false, '{system:menu-form:save}', '', 3, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '右键新建菜单', '', false, false, false, false, '{system:menu:create}', '', 3, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '右键删除菜单', '', false, false, false, false, '{system:menu:delete}', '', 3, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '新建页面按钮', '', false, false, false, false, '{system:menu-button:create}', '', 3, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '编辑页面按钮', '', false, false, false, false, '{system:menu-button:edit}', '', 3, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '删除页面按钮', '', false, false, false, false, '{system:menu-button:delete}', '', 3, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '菜单接口管理', '', false, false, false, false, '{system:menu-api:manager}', '', 3, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '保存权限', '', false, false, false, false, '{system:role-permission:save}', '', 7, 3, 0, now(), now());
INSERT INTO system_menu (path, name, component, redirect, title, hyperlink, is_hide, is_keep_alive, is_affix, is_iframe, auth, icon, parent, type, sort, create_time, update_time) VALUES ('', '', '', '', '接口权限管理', '', false, false, false, false, '{system:role-permission-api:manager}', '', 7, 3, 0, now(), now());

-- API分组
INSERT INTO system_api_group (name, remark, create_time, update_time) VALUES ('系统管理', '', '2021-09-05 10:25:43.667889 +00:00', '2021-09-05 10:49:02.592078 +00:00');

-- API接口
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('获取用户列表', '/api/v1/system/user', 'GET', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('获取用户详情', '/api/v1/system/user/info', 'GET', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('通过ID获取用户详情', '/api/v1/system/user/info/:id', 'GET', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('新建用户', '/api/v1/system/user', 'POST', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('编辑用户', '/api/v1/system/user/:id', 'PUT', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('删除用户', '/api/v1/system/user/:id', 'DELETE', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('获取菜单树', '/api/v1/system/menu/tree', 'GET', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('新建/编辑菜单', '/api/v1/system/menu', 'POST', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('删除菜单', '/api/v1/system/menu/:id', 'DELETE', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('批量删除菜单', '/api/v1/system/menu/batch', 'DELETE', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('获取菜单对应的按钮', '/api/v1/system/menu/button/:id', 'GET', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('菜单绑定/解绑接口', '/api/v1/system/menu/api/:id', 'POST', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('获取菜单绑定的接口', '/api/v1/system/menu/api/:id', 'GET', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('获取菜单对应的接口', '/api/v1/system/menu/api-list/:id', 'GET', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('获取角色列表', '/api/v1/system/role', 'GET', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('新建/编辑角色', '/api/v1/system/role', 'POST', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('删除角色', '/api/v1/system/role/:id', 'DELETE', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('角色授权/解除菜单权限', '/api/v1/system/role/permission/:id', 'POST', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('角色授权/解除接口权限', '/api/v1/system/role/api/:id', 'POST', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('获取角色授权的接口权限', '/api/v1/system/role/api/:id', 'GET', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('获取角色授权的菜单权限', '/api/v1/system/role/permission/:id', 'GET', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('获取接口列表', '/api/v1/system/api', 'GET', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('新建/编辑接口', '/api/v1/system/api', 'POST', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('删除接口', '/api/v1/system/api/:id', 'DELETE', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('接口分组列表', '/api/v1/system/api-group', 'GET', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('新建/编辑接口分组', '/api/v1/system/api-group', 'POST', 1, '', now(), now());
INSERT INTO system_api (title, url, method, "group", remark, create_time, update_time) VALUES ('删除接口分组', '/api/v1/system/api-group/:id', 'DELETE', 1, '', now(), now());

COMMIT;
-- 执行结束
